---
# tasks file for ansible-role-chrome

- include_tasks: debian.yml
  when: ansible_distribution in ('Debian', 'Ubuntu')

- include: redhat.yml
  when: ansible_distribution in ('Red Hat Enterprise Linux', 'CentOS', 'Fedora')
