---
# tasks file for ansible-role-chrome

- include_tasks: debian.yml
  when: ansible_distribution in ('Debian', 'Ubuntu')

- include_tasks: redhat.yml
  when: ansible_distribution in ('Red Hat Enterprise Linux', 'CentOS', 'Fedora')

- include_tasks: opensuse.yml
  when: '"openSUSE" in ansible_distribution'
